---
layout: post
title: "Lintr Bot, lintr's Hester egg"
comments: true
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE, 
                      cache = TRUE, eval = TRUE) 
```

Remember my blog post about [automatic tools for improving R packages](http://www.masalmon.eu/2017/06/17/automatictools/)? One of these tools is Jim Hester's `lintr`, a package that performs static code analysis. In my experience it mostly helps identifying too long code lines and missing space, although it's a bit more involved than that. In any case, `lintr` helps you maintain good code style, and as mentioned in that now old post of mine, you can add a `lintr` unit test to your package which will ensure you don't get lazy over time. 

Now say your package has a `lintr` unit test and lives on GitHub. What happens if someone makes a pull request and writes looong code lines? Continuous integration builds will fail but not only that... The contributor will get to know Lintr Bot, lintr's Hester (Easter) egg!


<!--more-->

# Lintr Bot, a lazy little thing?

Lintr Bot has a [GitHub profile](https://github.com/lintr-bot). I am actually responsible for its avatar, because when I discovered it a while back I offered Jim to design it based [on this free image](https://pixabay.com/en/cute-cartoon-robot-funny-character-807306/). Now, Lintr Bot has a face but if you look at its GitHub activity, you might wonder, what does it even do? It's perfectly fine for a human to have nearly no GitHub activity, but remember that Lintr Bot lives on GitHub only, so what does it do all day?

That's where my [`ghrecipes` package](http://www.masalmon.eu/2018/03/04/hrbrpkgs/), presented in [my blog post about Bob Rudis' R packages](http://www.masalmon.eu/2018/03/04/hrbrpkgs/), will come into play. I've been working on a function called `spy` which can return either Pull Requests or Issues an user commented on during a given period of time. As creepy as it might sound, it could help you trace back all the desperate comments you wrote when debugging something last week for instance, without your having had to track them in the first place. `ghrecipe::spy` is a work in progress, but let's see what it can return me for Lintr Bot!


Note, a good package to improve code style automatically is [`styler`](https://github.com/r-lib/styler) by Kirill Müller and Lorenz Walthert, so if Lintr Bot has a lot to tell you, give `styler::style_package()` a try! 